name: Track

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tracking
        run: |
          cd track
          python track.py
      - name: Check for changes
        run: git status
      - name: Stage changed files
        run: git add .
      - name: Commit changed files
        run: |
          git config --local user.email "argo.canada.bot@gmail.com"
          git config --local user.name "Argo Canada Bot"
          git commit -m "Auto updating DMQC tracker via cron job"
      - name: Fetch from main
        run: git fetch origin main
      - name: Push code to main
        run: git push origin HEAD:main

