name: Track

on: push

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas argopandas
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tracking
        run: |
          cd track
          python track.py

